#!/bin/bash

# ===========================================
# Spotify OAuth Token Generator
# ===========================================
# Reads CLIENT_ID and CLIENT_SECRET from .env file
# ===========================================

# Load .env file
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

REDIRECT_URI="http://127.0.0.1:8888/callback"
SCOPE="user-read-recently-played"
PORT=8888

# Check configuration
if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
    echo "Error: Please set CLIENT_ID and CLIENT_SECRET at the top of this script"
    exit 1
fi

# Build authorization URL
AUTH_URL="https://accounts.spotify.com/authorize?client_id=${CLIENT_ID}&response_type=code&redirect_uri=${REDIRECT_URI}&scope=${SCOPE}"

echo "Opening browser for Spotify authorization..."
echo ""

# Open browser (macOS)
open "$AUTH_URL"

echo "Waiting for callback on port $PORT..."
echo "(Authorize the app in your browser)"
echo ""

# Start a temporary server to catch the callback
# Using nc to listen for the redirect and extract the code
RESPONSE=$(nc -l $PORT <<EOF
HTTP/1.1 200 OK
Content-Type: text/html

<html><body><h1>Success!</h1><p>You can close this tab and return to your terminal.</p></body></html>
EOF
)

# Extract the authorization code from the request
CODE=$(echo "$RESPONSE" | grep -oP 'code=\K[^& ]+' | head -1)

# Fallback for macOS grep (no -P support)
if [ -z "$CODE" ]; then
    CODE=$(echo "$RESPONSE" | sed -n 's/.*code=\([^& ]*\).*/\1/p' | head -1)
fi

if [ -z "$CODE" ]; then
    echo "Error: Could not extract authorization code"
    echo "Response was:"
    echo "$RESPONSE"
    exit 1
fi

echo "Got authorization code!"
echo ""
echo "Exchanging for tokens..."
echo ""

# Exchange code for tokens
TOKEN_RESPONSE=$(curl -s -X POST https://accounts.spotify.com/api/token \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=authorization_code" \
    -d "code=${CODE}" \
    -d "redirect_uri=${REDIRECT_URI}" \
    -d "client_id=${CLIENT_ID}" \
    -d "client_secret=${CLIENT_SECRET}")

# Check for error
if echo "$TOKEN_RESPONSE" | grep -q "error"; then
    echo "Error getting tokens:"
    echo "$TOKEN_RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$TOKEN_RESPONSE"
    exit 1
fi

# Extract tokens
ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])" 2>/dev/null)
REFRESH_TOKEN=$(echo "$TOKEN_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['refresh_token'])" 2>/dev/null)

# Append tokens to .env
echo "" >> .env
echo "# Spotify tokens (generated by setup.sh)" >> .env
echo "SPOTIFY_ACCESS_TOKEN=${ACCESS_TOKEN}" >> .env
echo "SPOTIFY_REFRESH_TOKEN=${REFRESH_TOKEN}" >> .env

echo "Done! Tokens have been added to your .env file."
